[package]
name = "mewi"
version = "0.1.0"
description = "A tiny animated desktop cat."
authors = ["Mewi"]
edition = "2021"
license = "MIT"

[lib]
name = "mewi_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["macos-private-api", "tray-icon"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
